services:
  chatapp.server:
    image: chatapp.server
    ports:
      - "8079:8080"
    build:
      context: .
      dockerfile: src/bundles/ChatApp.Server/Dockerfile
    environment:
      ConnectionStrings:Postgres: "USER ID = postgres;PASSWORD = postgres;HOST = localhost;PORT = 5432;DATABASE = ChatApp;"
      
  chatapp.web:
    image: chatapp.web
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: src/bundles/ChatApp.Web/Dockerfile
      
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: ChatApp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: